### ISSUE TITLE
error when using the plugin in a node module

### ISSUE THREAD

**Issue by jeromecc** [bluwy/vite-plugin-iso-import#12]
Hi!

I use vite-plugin-iso-import successfully to import svelte-leafletjs in a component for my svelte kit project.

`import { Marker, LeafletMap, TileLayer, Tooltip } from 'svelte-leafletjs?client';`

I tried to put this component in a node module because i'm using it in many projects.

When I try to I got this error:

```
✘ [ERROR] Could not read from file: /home/elkcloner/git/clinic-cms/msp-gadagne-frontend/node_modules/svelte-leafletjs/dist/index.js?client

    node_modules/clinic-cms/dist/Map/Map.svelte:33:55:
      33 │ import { Marker, LeafletMap, TileLayer, Tooltip } from "svelte-leafletjs?client";
         ╵                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~

```

I checked, the file /home/elkcloner/git/clinic-cms/msp-gadagne-frontend/node_modules/svelte-leafletjs/dist/index.js does exist.

I really don't know how to solve this. Any clue?

Thanks a lot!

**Comment by bluwy** [comment]
Looks like the error comes from esbuild prebundling in Vite. I think this is somewhat expected at the moment because Vite prebundles library and assumes they're usually in compiled `.js` files etc, and doesn't run any Vite plugins to transform them, otherwise the whole process would also be very slow.

One solution in general for libraries that relies on Vite plugins is to mark the library under Vite's `optimizeDeps.exclude` option, that way the library won't be prebundled and will be processed normally by your Vite plugins. Maybe that works for you.

**Comment by jeromecc** [comment]
I added my library to optimizeDeps.exclude in vite.config.ts and it works. Thank you! :)

```
optimizeDeps: {
        include: ['lodash.get', 'lodash.isequal', 'lodash.clonedeep'],
	exclude: ['clinic-cms']
}
```
